[package]
name = "practice1"
version = "0.1.0"
authors = ["naufil <m.naufil1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pactice = {"/home/naufil/Desktop/rust_github/26Oct/practice"}